name: SoundEffects
main: com.bighatchet.soundeffects.SoundEffects
version: ${project.version}-b${BUILD_NUMBER}
authors: [mung3r]

commands:
  sound:
    description: SoundEffect commands
    usage: |
           Usage:
           /<command> list [page] - list sound names
           /<command> play <sound_name> [volume] [pitch] [count] [interval] - play a sound
permissions:
  soundeffects.command.*:
    description: Allows all commands
    children:
      soundeffects.command.list: true
      soundeffects.command.play: true
  soundeffects.command.list:
    description: List available sounds
    default: op
  soundeffects.command.play:
    description: Play a sound
    default: op